force-app/main/default/objects/Product_Image__c/Product_Image__c.object-meta.xml
<CustomObject>
    <label>Product Image</label>
    <nameField>
        <label>Product Image Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Images</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Image__c/fields/HeroImage__c.field-meta.xml
<CustomField>
    <fullName>HeroImage__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If Selected this image will be displayed on the Product List Page</inlineHelpText>
    <label>Hero Image</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Image__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The related product</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Images</relationshipLabel>
    <relationshipName>ProductImages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Image__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <inlineHelpText>The URL for the image</inlineHelpText>
    <label>URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/ProductImageController1.cls
/***********************************************************************************************
 * Author Name : Priyanka Korade
 * Class Name : ProductImageController1
 * Purpose : Controller for Product_Image__c object Controller Object related actions 
 * *********************************************************************************************/

public with sharing class ProductImageController1 {
     /*********************************************************************************************
     * Method Name : getAllProducts
     * Author Name : Priyanka Korade
     * purpose : Responsible fetching all Product Images
     * parameter : noparameter
     * *******************************************************************************************/
    @auraEnabled(cacheable = true)
    public static List<Product_Image__c> getAllProducts(){
        return [SELECT Product__r.Name,Product__r.Description, URL__c FROM Product_Image__c 
                WHERE HeroImage__c = true];
    }
}