force-app/main/default/objects/Address_Book__c/Address_Book__c.object-meta.xml
<CustomObject>
    <label>Address Book</label>
    <nameField>
        <label>Address Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address Books</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Address_Book__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <inlineHelpText>Customer city</inlineHelpText>
    <label>City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address_Book__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IND</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>ENG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address_Book__c/fields/Landmark__c.field-meta.xml
<CustomField>
    <fullName>Landmark__c</fullName>
    <inlineHelpText>the landmark for location detection</inlineHelpText>
    <label>Landmark</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address_Book__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <inlineHelpText>The area postal code</inlineHelpText>
    <label>Postal Code</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Address_Book__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <inlineHelpText>Customer State</inlineHelpText>
    <label>State</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AddressController.cls
/***********************************************************************************************
 * Author Name : Priyanka Korade
 * Class Name : AddressController
 * Purpose : Controller Class for Address_Book__c  Object related actions 
 * *********************************************************************************************/
public with sharing class AddressController {
    /*********************************************************************************************
     * Method Name : getAddress
     * Author Name : Priyanka Korade
     * purpose : Responsible For fetching All Addresses Related to current user 
     * parameter : noparameter
     * *******************************************************************************************/
    @AuraEnabled(cacheable=true)
    public static List<Address_Book__c> getAddress(){
        Id user = UserInfo.getUserId(); 
        // BillingStreet,BillingCity,BillingState,BillingCountry,BillingPostalCode,       
        return [SELECT Name,Street__c, City__c,Landmark__c,State__c , Country__c,PostalCode__c 
                FROM Address_Book__c WHERE CreatedById= :user];
    }

    @AuraEnabled(cacheable=true)
    public static List<Account> getBillingAddress(){
        Id user = UserInfo.getUserId(); 
        return [SELECT Name,BillingStreet,BillingCity,BillingState,BillingCountry,BillingPostalCode
                FROM Account WHERE CreatedById= :user];
    }
	
}