force-app/main/default/objects/Account_Request__c/Account_Request__c.object-meta.xml
<CustomObject>
    <label>Account Request</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>The status Of the Account</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open,</fullName>
                <default>true</default>
                <label>Open,</label>
            </value>
            <value>
                <fullName>In Process,</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined,</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountRequestTriggerTestClass.cls
@isTest
private class AccountRequestTriggerTestClass {
    static testMethod void validateAccountRequestTriggerHandler(){
        Account_Request__c acc= new Account_Request__c(Id='a085g000000tNlyAAE',Name='Priyanka',Status__c='Approved,');
        upsert acc;
        system.debug(acc.Name);
        List<Account> a = [SELECT Name FROM Account WHERE Name = :acc.Name];
        system.debug(a);
        system.assertEquals('Priyanka',a[0].Name);
    }
}