force-app/main/default/objects/Account_Request__c/Account_Request__c.object-meta.xml
<CustomObject>
    <label>Account Request</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Request__c/fields/BillingCity__c.field-meta.xml
<CustomField>
    <fullName>BillingCity__c</fullName>
    <label>BillingCity</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Request__c/fields/BillingCountry__c.field-meta.xml
<CustomField>
    <fullName>BillingCountry__c</fullName>
    <label>BillingCountry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India,</fullName>
            </value>
            <value>
                <fullName>USA,</fullName>
            </value>
            <value>
                <fullName>UK,</fullName>
            </value>
            <value>
                <fullName>South Africa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Request__c/fields/BillingPostalCode__c.field-meta.xml
<CustomField>
    <fullName>BillingPostalCode__c</fullName>
    <label>BillingPostalCode</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Request__c/fields/BillingState__c.field-meta.xml
<CustomField>
    <fullName>BillingState__c</fullName>
    <label>BillingState</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Request__c/fields/BillingStreet__c.field-meta.xml
<CustomField>
    <fullName>BillingStreet__c</fullName>
    <inlineHelpText>Address of the Customer</inlineHelpText>
    <label>BillingStreet</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Request__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <inlineHelpText>The Email for the Customer</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account_Request__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>Primary Contact LastName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Request__c/fields/PrimaryEmail__c.field-meta.xml
<CustomField>
    <fullName>PrimaryEmail__c</fullName>
    <inlineHelpText>The email of the primary Contact</inlineHelpText>
    <label>Primary Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account_Request__c/fields/PrimaryPhone__c.field-meta.xml
<CustomField>
    <fullName>PrimaryPhone__c</fullName>
    <inlineHelpText>The Phone Number of the primary Contact</inlineHelpText>
    <label>Primary Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account_Request__c/fields/ShippingCity__c.field-meta.xml
<CustomField>
    <fullName>ShippingCity__c</fullName>
    <label>ShippingCity</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Request__c/fields/ShippingCountry__c.field-meta.xml
<CustomField>
    <fullName>ShippingCountry__c</fullName>
    <label>ShippingCountry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India,</fullName>
            </value>
            <value>
                <fullName>USA,</fullName>
            </value>
            <value>
                <fullName>UK,</fullName>
            </value>
            <value>
                <fullName>South Africa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Request__c/fields/ShippingState__c.field-meta.xml
<CustomField>
    <fullName>ShippingState__c</fullName>
    <label>ShippingState</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>The status Of the Account</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open,</fullName>
                <default>true</default>
                <label>Open,</label>
            </value>
            <value>
                <fullName>In Process,</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined,</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountRequestTriggerHandler.cls
/*******************************************************************************************
ClassName: AccountRequestTriggerHandler
Author : Priyanka
CreatedDate : 18-03-2021
Purpose: Its an handler class for Account Request trigger
*******************************************************************************************/
public with sharing class AccountRequestTriggerHandler {
    /***********************************************************************************
	*MethodName:afterUpdateHandler
	*Parameters Accepted: trigger.new
	*Pupose: Creating an account when Account request status changes to approved
	************************************************************************************/
    public static void afterUpdateHandler(list<Account_Request__c> newList){
        Account[] accts = new List<Account>();
        Contact[] conts = new List<Contact>();
        
        for(Account_Request__c accReq : newList){
            if(accReq.Status__c=='Approved,'){
                Account acc = new Account();     
                acc.Name = accReq.Name;
                acc.Phone = accReq.Phone__c;
                acc.EmailId__c = accReq.Email__c;
                acc.Description = accReq.Description__c;                                
                acc.BillingStreet = accReq.BillingStreet__c;
                acc.BillingCity =  accReq.BillingCity__c;
                acc.BillingState = accReq.BillingState__c;
                acc.BillingCountry = accReq.BillingCountry__c;
                acc.BillingPostalCode = accReq.BillingPostalCode__c;
                acc.ShippingStreet = accReq.ShippingStreet__c;
                acc.ShippingCity = accReq.ShippingCity__c; 
                acc.ShippingState = accReq.ShippingState__c;   
                acc.ShippingCountry = accReq.ShippingCountry__c;                                
                acc.ShippingPostalCode = accReq.ShippingPostalCode__c; 
                
                Contact con = new Contact();
                con.FirstName = accReq.FirstName__c;
                con.LastName = accReq.LastName__c;
                con.Email = accReq.PrimaryEmail__c;
                con.Phone = accReq.PrimaryPhone__c;
                con.Title = accReq.PrimaryTitle__c; 
                
                accts.add(acc);        
                conts.add(con);
            }
        }
        try{
            if(accts.size()>0)
            	insert accts;
        }catch(Exception e){
            system.debug(e.getMessage());
        } 
        for(Integer i=0 ; i<conts.size();i++){
            conts[i].AccountId=accts[i].id;
        }
        try{
            if(conts.size()>0)
            	insert conts;
        }catch(Exception e){
            system.debug(e.getMessage());
        }
    }
}