force-app/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <label>Cart</label>
    <nameField>
        <displayFormat>Cart-{0000}</displayFormat>
        <label>Cart #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Total Amount</label>
    <summarizedField>Cart_Item__c.TotalAmount__c</summarizedField>
    <summaryForeignKey>Cart_Item__c.Cart__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Cart__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <inlineHelpText>The customer record who have created the cart</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Carts</relationshipLabel>
    <relationshipName>Carts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cart__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>The status of the cart. By default all carts will be open and only one cart can be open for a customer at a time</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cart_Item__c/Cart_Item__c.object-meta.xml
<CustomObject>
    <label>Cart Item</label>
    <nameField>
        <displayFormat>Item-{0000}</displayFormat>
        <label>Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product record which is added as item under the cart record</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>Cart_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cart_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <inlineHelpText>The total no of items to be included into the cart</inlineHelpText>
    <label>Quantity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cart_Item__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <formula>Quantity__c  *  Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <inlineHelpText>Parent Account related to customer</inlineHelpText>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/AmountPaid__c.field-meta.xml
<CustomField>
    <fullName>AmountPaid__c</fullName>
    <inlineHelpText>The amout which has been paid for order record.</inlineHelpText>
    <label>Paid Amount</label>
    <summarizedField>Payment__c.Amount__c</summarizedField>
    <summaryForeignKey>Payment__c.Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The customer record under which order is created</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/ExpectedDate__c.field-meta.xml
<CustomField>
    <fullName>ExpectedDate__c</fullName>
    <inlineHelpText>The expected delivery date of the order</inlineHelpText>
    <label>Expected Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COD</fullName>
            </value>
            <value>
                <fullName>Net Banking</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
            </value>
            <value>
                <fullName>Debit Card</fullName>
            </value>
            <value>
                <fullName>EMI</fullName>
            </value>
            <value>
                <fullName>Wallet</fullName>
            </value>
            <value>
                <fullName>Banking,</fullName>
                <isActive>false</isActive>
                <label>Banking,</label>
            </value>
            <value>
                <fullName>Card,</fullName>
                <isActive>false</isActive>
                <label>Card,</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/PaymentStatus__c.field-meta.xml
<CustomField>
    <fullName>PaymentStatus__c</fullName>
    <inlineHelpText>Status of the Payment for the order</inlineHelpText>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PAID</fullName>
            </value>
            <value>
                <fullName>COD</fullName>
            </value>
            <value>
                <fullName>Partially</fullName>
            </value>
            <value>
                <fullName>EMI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <label>Shipping Address</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Status of the Order Record</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open,</fullName>
            </value>
            <value>
                <fullName>In Process,</fullName>
            </value>
            <value>
                <fullName>Dispatched,</fullName>
            </value>
            <value>
                <fullName>Shipped,</fullName>
            </value>
            <value>
                <fullName>Out for Delivery,</fullName>
            </value>
            <value>
                <fullName>Delivered,</fullName>
            </value>
            <value>
                <fullName>Closed,</fullName>
            </value>
            <value>
                <fullName>Return Requested,</fullName>
            </value>
            <value>
                <fullName>Returned,</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Totalitems__c.field-meta.xml
<CustomField>
    <fullName>Totalitems__c</fullName>
    <inlineHelpText>The order quantity</inlineHelpText>
    <label>Total items</label>
    <summarizedField>Order_Line_Item__c.Quantity__c</summarizedField>
    <summaryForeignKey>Order_Line_Item__c.Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/ListPrice__c.field-meta.xml
<CustomField>
    <fullName>ListPrice__c</fullName>
    <inlineHelpText>The list price of item</inlineHelpText>
    <label>List Price</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <inlineHelpText>The related order</inlineHelpText>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The item to be included</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <inlineHelpText>The total no of items to be included  in the order</inlineHelpText>
    <label>Quantity</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <inlineHelpText>The total amount for the item</inlineHelpText>
    <label>Total</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <inlineHelpText>The actual price of item</inlineHelpText>
    <label>Unit Price</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/OrderController.cls
/***********************************************************************************************
 * Author Name : Abhisek Paliwal, Sandesh Sawant
 * Class Name : OrderController
 * Purpose : Controller Class for Order__c Object related actions 
 * *********************************************************************************************/
public with sharing class OrderController {
    /*********************************************************************************************
     * Method Name : createOrder
     * Author Name : Abhishek Paliwal
     * purpose : Creates Order  And OrderLine items related to cart 
     * parameter : String addr Shipping Address
     * *******************************************************************************************/
    @AuraEnabled
    public static Id createOrder(Id cartId){
        System.debug('cartId : '+cartId);
        Order__c order;
        String userId=UserInfo.getUserId();
        Cart__c cart=[ SELECT  CreatedById, Quantity__c, Amount__c,
                (select Product__r.Name,Product__r.Description, Product__r.Price__c,Product__r.Id,Quantity__c,TotalAmount__c  
                From cart_Items__r) 
                FROM cart__c 
                WHERE Id = : cartId];
        Contact cust=[SELECT  Account.Id,Id FROM Contact WHERE OwnerId =: userId LIMIT 1];
        List<Order__c> orderList=[SELECT Id, Name, Customer__c,
                            Status__c, BillingAddress__c,
                          PaymentStatus__c, DeliveredDate__c,
                          ExpectedDate__c, PaymentMethod__c,
                          AccountName__c, Totalitems__c, Total__c,
                          AmountPaid__c, Shipping_Address__c 
                          FROM Order__c WHERE Status__c='Open,' AND
                         Customer__c = : cust.Id] ;
        List<Order_Line_Item__c> oliList=new List<Order_Line_Item__c>();
        if(orderList.size() > 0){
            order=orderList[0];
        }
        else {
            order=new Order__c(Customer__c=cust.Id,
                                Status__c='Open,',
                                //PaymentStatus__c= pymtMode,
    							//ExpectedDate__c=system.today().addDays(3),
                                //PaymentMethod__c= pymtMode,
                                AccountName__c=cust.Account.Id
                                //,Shipping_Address__c= addr
    							);
            insert order;
        }
            for(Cart_Item__c ci : cart.cart_Items__r){
                Order_Line_Item__c oli=new Order_Line_Item__c(
                Name=ci.Product__r.Name,
                Product__c=ci.Product__r.Id,
                Quantity__c=ci.Quantity__c,
                Total__c=ci.TotalAmount__c,
                UnitPrice__c=ci.Product__r.Price__c,
                Order__c =order.Id
                );
                oliList.add(oli);
            }
            insert oliList;
            cart.Status__c='Closed';
            update cart;
            return order.Id;
    }
    /*********************************************************************************************
     * Method Name : getOpenOrder
     * Author Name : Abhishek Paliwal
     * purpose : fetches Open Order Record Related to current user
     * parameter : no parameter
     * *******************************************************************************************/
    @AuraEnabled(cacheable=true)
    public static List<Order__c> getOpenOrder(){
        Id uid=UserInfo.getUserId();
        List<Order__c> orderList=[SELECT Id,PaymentStatus__c, DeliveredDate__c, ExpectedDate__c, PaymentMethod__c, Totalitems__c, Total__c, AmountPaid__c, Shipping_Address__c 
                       ,(SELECT Id, Name, Product__c, Quantity__c, Total__c, ListPrice__c, UnitPrice__c, Order__c FROM Order_Line_Items__r)
                       FROM Order__c
                       WHERE Status__c='Open,' AND Customer__c IN (SELECT Id FROM Contact WHERE OwnerId= : uid)];
        return orderList;
        
    }

    /*********************************************************************************************
     * Method Name : updateOrderStatus
     * Author Name : Abhishek Paliwal
     * purpose : Updates The order Status 
     * parameter : 1. Id Of the Order, 2. Status Of the order
     * *******************************************************************************************/
    @AuraEnabled
    public static void updateOrderStatus(String id,String status){
        Order__c order=[SELECT Status__c FROM Order__c WHERE Id= :id];
        if(order.Status__c == 'Open,'){
            throw new CustomException('Order Not Placed Yet');
        }
        order.Status__c=status;
        update order;
    }
    /*********************************************************************************************
     * Method Name : getOrderDetail
     * Author Name : Sandesh Sawant
     * purpose : fetches Order Details, pagination  and also searching was done
     * parameter : 1. offset 2. Limit 3.SerachKey
     * *******************************************************************************************/
    @AuraEnabled(cacheable=True)
    public static List<Order__c> getOrderDetail(Integer offset, Integer l,String searchKey){
        Id uid=UserInfo.getUserId();
        String searchKeyword = '%' + searchKey + '%';
        

        List<Order__c> orderListRecord = new List<Order__c>();
        
        for(Order__c ordObj : [SELECT Name,ExpectedDate__c,Total__c,BillingAddress__c,Shipping_Address__c,Status__c
        FROM Order__c WHERE Name Like :searchKeyword AND  Customer__c IN (SELECT Id FROM Contact WHERE OwnerId= : uid )limit :l  offset :offset]){
            orderListRecord.add(ordObj);
        }
        return orderListRecord;
    }
    /************************************************************************************
     *  Method Name : getOrderByDate
     * Author Name : Sandesh Sawant
     * purpose : it fetches the data between two dates
     * parameter : 1.FirstDate  2. LastDate 
     
     *****************************************************************************************/
    @AuraEnabled(cacheable = true)
    public static List<Order__c> getOrderByDate(date FirstDate,date LastDate){
        return[SELECT Name,ExpectedDate__c,Total__c,BillingAddress__c,Shipping_Address__c,Status__c
        FROM Order__c WHERE (ExpectedDate__c >= :FirstDate AND ExpectedDate__c <= :LastDate)];
        
    }
    
    
    /*********************************************************************************************
     * Method Name : getOrderById
     * Author Name : Sandesh Sawant
     * purpose : fetches Order Details by id
     * parameter : 1. Takes OrderId as a parameter
     * *******************************************************************************************/
    @AuraEnabled(cacheable=True)
    public static List<Order__c> getOrderById(id orderID){
        return [SELECT Id,PaymentStatus__c, DeliveredDate__c, ExpectedDate__c, PaymentMethod__c, Totalitems__c, Total__c, AmountPaid__c, Shipping_Address__c 
        ,(SELECT Id, Name, Product__c, Quantity__c, Total__c FROM Order_Line_Items__r)
        FROM Order__c
        WHERE Id = :orderID];
        
    }

     /*********************************************************************************************
     * Method Name : getPaymentMethods
     * Author Name : Abhishek Paliwal
     * purpose : fetches All Payment Methods Of  Order Object
     * parameter : No
     * *******************************************************************************************/
    @AuraEnabled(cacheable=true)
    public static List<string> getPaymentMethods(){
        List<String> methods= new List<String>();
        schema.DescribeFieldResult fd = Order__c.PaymentMethod__c.getdescribe();
        list<schema.picklistentry> pc = fd.getpicklistvalues();
        
        for(schema.picklistentry f: pc){
        	system.debug('label  : '+ f.getlabel()+' Value : '+f.getvalue());
            methods.add(f.getvalue());
        }
        return methods;
    }
    
     /*********************************************************************************************
     * Method Name : updateAddr
     * Author Name : Abhishek Paliwal
     * purpose : Updates the addressh of the order
     * parameter : two parameters 1 Order Id 2. Address
     * *******************************************************************************************/
    @AuraEnabled
    public static void updateAddr(Id orderId, String addr){
       Order__c ord=[SELECT Shipping_Address__c FROM Order__c WHERE Id= :orderId];
       ord.Shipping_Address__c=addr;
       try {
           update ord;
       } catch (Exception e) {
           throw new CustomException('Cannot Deliver To this address');
       }
    }

     /*********************************************************************************************
     * Method Name : updatePaymentMethod
     * Author Name : Abhishek Paliwal
     * purpose : Updates the PaymentMethod ,status, delivery date,
     * parameter : two parameters 1 Order Id 2. Payment Method
     * *******************************************************************************************/
    @AuraEnabled
    public static void updatePaymentMethod(Id orderId,String method){
        Order__c ord=[SELECT PaymentStatus__c,Status__c,ExpectedDate__c, PaymentMethod__c FROM Order__c WHERE Id= : orderId];
        ord.PaymentStatus__c=method;
        ord.ExpectedDate__c=system.today().addDays(3);
        ord.PaymentMethod__c= method;
        ord.Status__c='In Process,';
        try {
            update ord;
        } catch (Exception e) {
            throw new CustomException('Cannot place order');
        }
    }
}