force-app/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <label>Cart</label>
    <nameField>
        <displayFormat>Cart-{0000}</displayFormat>
        <label>Cart #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Total Amount</label>
    <summarizedField>Cart_Item__c.TotalAmount__c</summarizedField>
    <summaryForeignKey>Cart_Item__c.Cart__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Cart__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <inlineHelpText>The customer record who have created the cart</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Carts</relationshipLabel>
    <relationshipName>Carts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cart__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>The status of the cart. By default all carts will be open and only one cart can be open for a customer at a time</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cart_Item__c/Cart_Item__c.object-meta.xml
<CustomObject>
    <label>Cart Item</label>
    <nameField>
        <displayFormat>Item-{0000}</displayFormat>
        <label>Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product record which is added as item under the cart record</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>Cart_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cart_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <inlineHelpText>The total no of items to be included into the cart</inlineHelpText>
    <label>Quantity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cart_Item__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <formula>Quantity__c  *  Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CartController.cls
/***********************************************************************************************
 * Author Name : Abhishek Paliwal
 * Class Name : CartController
 * Purpose : Controller Class for Cart__c  Object related actions 
 * *********************************************************************************************/
public with sharing class CartController {
    
    /*********************************************************************************************
     * Method Name : addItemToCart
     * Author Name : Abhishek Paliwal
     * purpose : Responsible Adding Item to the cart 
     * parameter : 1. String prodId Id Of the Product to add
     * 			   2. Quantity Of the product
     * *******************************************************************************************/
    @AuraEnabled
    public static Boolean addItemToCart(String prodId,Integer quantity){
        Product2 prod=[SELECT Id, Name, TotalQuantity__c, RemainingQuantity__c, Discount__c, Price__c FROM Product2 WHERE id=:prodId ];
            String userId =UserInfo.getUserId();
            List<Contact> cust=[SELECT id FROM Contact WHERE OwnerId= : userId LIMIT 1];
            List<Cart__c> cartlist=[SELECT Name,Quantity__c,Amount__c 
                            FROM Cart__c 
                            WHERE Status__c='Open' AND
                            Customer__c IN : cust
                            LIMIT 1];
            if(cartlist.size()>0){
                String cartId =cartlist[0].id;
                double amount=prod.Price__c;
                Integer qty=quantity;
                Cart_Item__c item=new Cart_Item__c(Cart__c=cartId,Amount__c=amount,Quantity__c=qty,Product__c=prod.Id);
                try {
                    insert item;
                } catch (Exception e) {
                    system.System.debug(e.getMessage());
                }
            }else{
                Cart__c cart=new Cart__c(Status__c='Open',Customer__c= cust[0].id);
                try{
                    insert cart;
                }catch(Exception e){
                    system.debug(e.getMessage());
                }
                String cartId =cart.Id;
                double amount=prod.Price__c;
                Integer qty=quantity;
                Cart_Item__c item=new Cart_Item__c(Cart__c=cartId,Amount__c=amount,Quantity__c=qty,Product__c=prod.Id);
                    try {
                    insert item;
                } catch (Exception e) {
                    system.System.debug(e.getMessage());
                }
            }
            return true;
    }
	
    /*********************************************************************************************
     * Method Name : getOpenCart
     * Author Name : Abhishek Paliwal
     * purpose : It Fetches The Open cart Information with Cart Item
     * parameter : noparameter
     * *******************************************************************************************/
    @AuraEnabled(cacheable=true)
    public static List<Cart__c> getOpenCart(){
        String userId= UserInfo.getUserId();
        return [SELECT  CreatedById, Quantity__c, Amount__c,(select Product__r.Name,Product__r.Description, Product__r.Price__c,Amount__c,Product__r.Id,Quantity__c,TotalAmount__c  From cart_Items__r) 
        FROM cart__c WHERE Status__c='Open' AND Customer__c IN (SELECT id FROM Contact WHERE OwnerId =: userId) LIMIT 1];
    }

 /*   @AuraEnabled
    public static void closeTheCart(){
        String uid =UserInfo.getUserId();
        Cart__c cart=[SELECT Status__c FROM Cart__c WHERE Status__c='Open' AND Customer__c IN (SELECT Id FROM Contact WHERE OwnerId= : uid  ) LIMIT 1];
        cart.Status__c='Closed';
        update cart;
    }
   */ 

}