force-app/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <label>Cart</label>
    <nameField>
        <displayFormat>Cart-{0000}</displayFormat>
        <label>Cart #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart_Item__c/Cart_Item__c.object-meta.xml
<CustomObject>
    <label>Cart Item</label>
    <nameField>
        <displayFormat>Item-{0000}</displayFormat>
        <label>Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product record which is added as item under the cart record</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>Cart_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cart_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <inlineHelpText>The total no of items to be included into the cart</inlineHelpText>
    <label>Quantity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AddToCartController.cls
/***********************************************************************************************
ClassName: AddToCartController
Author : Priyanka
CreatedDate : 24-03-2021
Purpose: Handles Add to cart functionality of product detail page
***********************************************************************************************/
public with sharing class AddToCartController {
    /********************************************************************************************
    *MethodName:addProductToCart
    *Parameters Accepted: (ProductId which is to be added to cart, Quantity of product)
    *Pupose: Add to product to cart and if product already exists in the cart increase the 
             quantity in the cart
    ********************************************************************************************/
    @AuraEnabled
    public static void addProductToCart(String Id,Double qty){
        
        cart_Item__c items;
        Id user = UserInfo.getUserId();
        cart__c cart = [SELECT CreatedById FROM cart__c WHERE CreatedById= :user];
        List<cart_Item__c> itemList = [SELECT Product__c,Quantity__c FROM cart_Item__c WHERE cart__c= :cart.Id];
        List<Id> idList = new List<ID>();
        for(cart_Item__c i: itemList){
            idList.add(i.product__c);
        }   
        try {
            if(cart.CreatedById==user){
                if(idList.contains(Id)){
                    
                    items=new cart_Item__c(cart__c=cart.Id,Product__c=Id,Quantity__c=qty);
                }else{
                 items=new cart_Item__c(cart__c=cart.Id,Product__c=Id,Quantity__c=qty);
                }
            }   
                upsert items;            
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
}