force-app/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <label>Cart</label>
    <nameField>
        <displayFormat>Cart-{0000}</displayFormat>
        <label>Cart #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Total Amount</label>
    <summarizedField>Cart_Item__c.TotalAmount__c</summarizedField>
    <summaryForeignKey>Cart_Item__c.Cart__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Cart_Item__c/Cart_Item__c.object-meta.xml
<CustomObject>
    <label>Cart Item</label>
    <nameField>
        <displayFormat>Item-{0000}</displayFormat>
        <label>Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product record which is added as item under the cart record</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>Cart_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cart_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <inlineHelpText>The total no of items to be included into the cart</inlineHelpText>
    <label>Quantity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Coupon__c/Coupon__c.object-meta.xml
<CustomObject>
    <label>Coupon</label>
    <nameField>
        <label>Coupon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Coupon__c/fields/Expired__c.field-meta.xml
<CustomField>
    <fullName>Expired__c</fullName>
    <formula>ExpiryDate__c  &lt;  TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates if the coupon is expired or not</inlineHelpText>
    <label>Expired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Coupon__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <inlineHelpText>The total no of discount coupons available</inlineHelpText>
    <label>Total Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Coupon__c/fields/RemainingQuantity__c.field-meta.xml
<CustomField>
    <fullName>RemainingQuantity__c</fullName>
    <inlineHelpText>Total no of discount coupons availble</inlineHelpText>
    <label>Remaining Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Coupon__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>The type of discount</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flat</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/cartItems.cls
/***********************************************************************************************
ClassName: cartItems
Author : Priyanka
CreatedDate : 22-03-2021
Purpose: Handles cart Items page
***********************************************************************************************/
public with sharing class cartItems {
    /********************************************************************************************
    *MethodName:getAllCartItems
    *Parameters Accepted: None
    *Pupose: Handles cart details page
    ********************************************************************************************/
    @AuraEnabled(cacheable=true)
    public static List<Cart__c> getAllCartItems(){
        Id user = UserInfo.getUserId();
        List<Cart__c> cartList = [SELECT  CreatedById, Quantity__c, Amount__c,(select Product__r.Name,Product__r.Description, Product__r.Price__c From cart_Items__r) 
                                        FROM cart__c WHERE CreatedById = : user ];
        return cartList ;                               
    }
    /********************************************************************************************
    *MethodName:getCoupons
    *Parameters Accepted: None
    *Pupose: Fetches all the coupons available in the system 
    ********************************************************************************************/
    @AuraEnabled(cacheable=true)
    public static List<Coupon__c> getCoupons(){
        List<Coupon__c> coupons = [SELECT Name, Expired__c, Type__c FROM Coupon__c];
        return coupons;
    }
    
    /********************************************************************************************
    *MethodName:updateAmount
    *Parameters Accepted: None
    *Purpose: update the cart Item with given Quantity
    ********************************************************************************************/
    @AuraEnabled
    public static void updateAmount(Cart_Item__c item,Double amount){
        system.debug('item : '+item);
        item.Amount__c=amount;
        update item;
    }



    /********************************************************************************************
    *MethodName:updateCartItem
    *Parameters Accepted: None
    *Purpose: update the cart Item with given Quantity
    ********************************************************************************************/
    @AuraEnabled
    public static void updateCartItem(String id,Integer qty){
        system.debug(id + '  '+qty);
        Cart_Item__c ci=[SELECT Quantity__c,Product__r.RemainingQuantity__c FROM Cart_Item__c WHERE Id= : id];
        
        if(qty <= ci.Product__r.RemainingQuantity__c && qty > 0){
            ci.Quantity__c=qty;
            update ci;
        }
        else
            throw new CustomException('Product Out Of stocks');
    }
}