force-app/main/default/objects/Coupon__c/Coupon__c.object-meta.xml
<CustomObject>
    <label>Coupon</label>
    <nameField>
        <label>Coupon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Coupon__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Coupon__c/fields/Expired__c.field-meta.xml
<CustomField>
    <fullName>Expired__c</fullName>
    <formula>ExpiryDate__c  &lt;  TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates if the coupon is expired or not</inlineHelpText>
    <label>Expired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Coupon__c/fields/RemainingQuantity__c.field-meta.xml
<CustomField>
    <fullName>RemainingQuantity__c</fullName>
    <inlineHelpText>Total no of discount coupons availble</inlineHelpText>
    <label>Remaining Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CouponController.cls
/*************************************************************************************
 * Author Name : Abhishek Paliwal
 * Class Name : CouponController
 * Purpose : Controller for coupon related actions
 ************************************************************************************/
public with sharing class CouponController {
    
    /***************************************************************************************
     * Method Name : validateCoupon
     * Purpose : returns Coupon by name
     * Parameter : one parameter Coupon name
     ******************************************************************************************/
    @AuraEnabled(cacheable=true)
    public static Coupon__c getCoupon(String couponCode){
        return [SELECT id,Discount__c,RemainingQuantity__c,Expired__c FROM Coupon__c WHERE Name = : couponCode AND Expired__c != true  LIMIT 1];
    } 
}