force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Product Categories</relationshipLabel>
    <relationshipName>ProductCategories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Category__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The product for the category</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Categories</relationshipLabel>
    <relationshipName>ProductCategories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CategoryController.cls
/***********************************************************************************************
 * Author Name : Abhisek Paliwal
 * Class Name : CategoryController
 * Purpose : Controller Class for Category__c  Object related actions 
 * *********************************************************************************************/
public with sharing class CategoryController {
    
    /*********************************************************************************************
     * Method Name : createOrder
     * Author Name : Abhishek Paliwal
     * purpose : Responsible For fetching Categories 
     * parameter : noparameter
     * *******************************************************************************************/
    @AuraEnabled(cacheable=true)
    public static List<Category__c> getCategories(){
        return [SELECT Id, Name, ParentCategory__c, (SELECT Name,id FROM Categories__r) FROM Category__c WHERE ParentCategory__c = null];
    }
	
    /*********************************************************************************************
     * Method Name : createOrder
     * Author Name : Abhishek Paliwal
     * purpose : Responsible For fetching Product Category Using Category Id  
     * parameter : 1. String Id Id Of the Category
     * *******************************************************************************************/
    @AuraEnabled(cacheable=true)
    public static List<Product_Category__c> getProductsByCategory(String id){
        return [SELECT  Product__c FROM Product_Category__c WHERE  Category__c= : id];
    }
}